# Generated by Django 6.0.4 on 2026-04-16 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(help_text='ID del archivo en GridFS de MongoDB', max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, help_text='OEM asociado (VW, BMW, etc.)', max_length=100, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_indexed', models.BooleanField(default=False, help_text='Indica si el documento ya ha sido procesado por el RAG')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Usuario',
                'verbose_name_plural': 'Documentos de Usuarios',
            },
        ),
    ]
