"""
Django settings for mechanics project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR is now /app/src, PROJECT_ROOT is /app
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent  # /app
BASE_DIR = Path(__file__).resolve().parent.parent  # /app/src


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-default-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# ALLOWED_HOSTS = ['ernestoavedillo.com', '204.168.206.76', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = ['*']
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'menuapp',
    'muelles',
    'tolerances',
    'specs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mechanics.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'mechanics.wsgi.application'


# Database - Configuration for SQLite (needed for sessions)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': PROJECT_ROOT / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', None),
        'USER': os.environ.get('POSTGRES_USER', None),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', None),
        'HOST': os.environ.get('POSTGRES_HOST', None),
        'PORT': os.environ.get('POSTGRES_PORT', None),
    }
}

# Language and timezone configuration
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'Europe/Madrid'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

# Login config
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# HTTPS/SSL Configuration
# In development (when DEBUG=True), NEVER redirect to HTTPS
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_DOMAIN = None
    CSRF_TRUSTED_ORIGINS = [
        'http://127.0.0.1',
        'http://localhost',
        'http://localhost:8000',
        'http://django:8000',
    ]
else:
    # In production
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    CSRF_COOKIE_DOMAIN = 'ernestoavedillo.com'
    CSRF_TRUSTED_ORIGINS = [
        'https://ernestoavedillo.com',
        'https://www.ernestoavedillo.com',
    ]

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# CSRF Configuration
# (Configured above in the if DEBUG block)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# Points to assets/ where the files are
STATICFILES_DIRS = [PROJECT_ROOT / 'assets']
# Django collects here in production
STATIC_ROOT = PROJECT_ROOT / 'static_files/'

# Email configuration (use environment variables in production)
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.example.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = 'noreply@ernestoavedillo.com'

# MongoDB and Qdrant configuration
import urllib.parse

MONGO_DB_NAME = os.environ.get('MONGO_INITDB_DATABASE', os.environ.get('MONGO_DB_NAME', 'mechanics'))
_mongo_user = os.environ.get('MONGO_INITDB_ROOT_USERNAME', '')
_mongo_pass = os.environ.get('MONGO_INITDB_ROOT_PASSWORD', '')
_mongo_host = os.environ.get('MONGO_HOST', 'mongodb')
_mongo_port = os.environ.get('MONGO_PORT', '27017')

if _mongo_user and _mongo_pass:
    _mongo_pass_encoded = urllib.parse.quote_plus(_mongo_pass)
    _default_mongo_url = f"mongodb://{_mongo_user}:{_mongo_pass_encoded}@{_mongo_host}:{_mongo_port}/?authSource=admin"
else:
    _default_mongo_url = f"mongodb://{_mongo_host}:{_mongo_port}/"

MONGO_URL = os.environ.get('MONGO_URL', _default_mongo_url)
QDRANT_URL = os.environ.get('QDRANT_URL', 'http://qdrant:6333')
QDRANT_API_KEY = os.environ.get('QDRANT_API_KEY', '')
LLAMA_CLOUD_API_KEY = os.environ.get('LLAMA_CLOUD_API_KEY', '')
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY', '')
GOOGLE_MODEL = os.environ.get('GOOGLE_MODEL', 'models/gemini-3.1-flash-lite-preview')
HF_MODEL = os.environ.get('HF_MODEL', 'BAAI/bge-m3')
HF_TOKEN = os.environ.get('HF_TOKEN', '')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Celery Beat - Periodic tasks
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'retry-pending-documents': {
        'task': 'specs.tasks.retry_pending_documents',
        'schedule': crontab(minute='*/10'),  # Cada 1 minutos
    },
    'remove-pending-registrations': {
        'task': 'menuapp.tasks.remove_pending_registration',
        'schedule': crontab(minute='*/15'),  # Cada 15 minutos
    }
}
