"""
Django settings for mechanics project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR ahora es /app/src, PROJECT_ROOT es /app
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent  # /app
BASE_DIR = Path(__file__).resolve().parent.parent  # /app/src


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-default-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# ALLOWED_HOSTS = ['ernestoavedillo.com', '204.168.206.76', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = ['*']
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'menuapp',
    'muelles',
    'tolerances',
    'specs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mechanics.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mechanics.wsgi.application'


# Database - Configuración para SQLite (necesaria para sessions)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': PROJECT_ROOT / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', None),
        'USER': os.environ.get('POSTGRES_USER', None),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', None),
        'HOST': os.environ.get('POSTGRES_HOST', None),
        'PORT': os.environ.get('POSTGRES_PORT', None),
    }
}

# Configuración de idioma y zona horaria
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'Europe/Madrid'
USE_I18N = False
USE_TZ = True

# Login config
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# HTTPS/SSL Configuration
# En desarrollo (cuando DEBUG=True), NUNCA redirigir a HTTPS
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_DOMAIN = None
    CSRF_TRUSTED_ORIGINS = [
        'http://127.0.0.1',
        'http://localhost',
        'http://localhost:8000',
        'http://django:8000',
    ]
else:
    # En producción
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    CSRF_COOKIE_DOMAIN = 'ernestoavedillo.com'
    CSRF_TRUSTED_ORIGINS = [
        'https://ernestoavedillo.com',
        'https://www.ernestoavedillo.com',
    ]

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# CSRF Configuration
# (Configurado arriba en el bloque if DEBUG)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [PROJECT_ROOT / 'assets']  # Apunta a assets/ donde están los archivos
STATIC_ROOT = PROJECT_ROOT / 'static_files/'  # Django colecta aquí en producción

# Configuración de email (usar variables de entorno en producción)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@ernestoavedillo.com'
MUELLES_MATERIAL_DIR = BASE_DIR / 'muelles' / 'material'
MUELLES_MATERIALS_CSV = MUELLES_MATERIAL_DIR / 'materials.csv'

# Configuración de MongoDB y Qdrant
MONGO_DB_NAME = os.environ.get('MONGO_DB_NAME', 'mechanics_db')
MONGO_URL = os.environ.get('MONGO_URL', 'mongodb://mongodb:27017/')
QDRANT_URL = os.environ.get('QDRANT_URL', 'http://qdrant:6333')
LLAMA_CLOUD_API_KEY = os.environ.get('LLAMA_CLOUD_API_KEY', '')


